name: widam
description: Browse our products with ease and choose your favorite meat cut and complete your order by choosing your preferred payment method.

publish_to: 'none'

version: 20.0.1+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  auto_route: ^7.8.4
  intl: ^0.18.1
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  flutter_native_splash: ^2.3.5
  flutter_svg: ^2.0.9
  google_maps_flutter: ^2.5.0
  modal_bottom_sheet: ^3.0.0-pre
  geocoding: ^2.1.1
  uuid: ^3.0.6
  dio: ^5.3.3
  geolocator: ^10.1.0
  mockito: ^5.4.3
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  pull_to_refresh: ^2.0.0
  queen_validators: ^1.0.1  
  flutter_staggered_grid_view: ^0.7.0
  pinput: ^3.0.0
  timer_count_down: ^2.2.2
  easy_stepper: ^0.8.2
  flutter_keyboard_visibility: ^5.4.1
  dotted_border: ^2.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  url_launcher: ^6.2.1
  package_info_plus: ^4.2.0
  webview_flutter: ^4.4.2
  pay: ^1.1.2
  fcm_config: 
    path: local_packages/fcm_config
  store_redirect: ^2.0.1
  flutter_html: ^3.0.0-beta.2
  flutter_barcode_scanner: ^2.0.0
  firebase_crashlytics: ^3.4.4
  firebase_core: ^2.22.0
  onboarding_overlay: ^3.2.1
  flutter_rating_bar: ^4.0.1
  widget_to_marker: ^1.0.4
  flutter_polyline_points_plus: ^3.0.0
  step_progress_indicator: ^1.0.2
  synchronized: ^3.1.0
  flutter_vibrate: ^1.3.0
  flutter_cupertino_date_picker_fork: ^1.0.7
  firebase_database: ^10.3.4
  firebase_ui_database: ^1.3.12
  firebase_auth: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.3
  flutter_gen_runner: ^5.3.2
  riverpod_lint: ^1.3.2
  custom_lint: ^0.4.0
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/app_icon/app_icon.png"
  remove_alpha_ios: true

flutter_gen:
  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/splash/logo.png
    - assets/splash/splash.gif

  fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        weight: 400
      - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        weight: 700
      - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
        weight: 800
  - family: Qatar
    fonts:
      - asset: assets/fonts/qatar/Qatar2022Arabic-Thin.ttf
        weight: 100
      - asset: assets/fonts/qatar/Qatar2022Arabic-Book.ttf
        weight: 400
      - asset: assets/fonts/qatar/Qatar2022Arabic-Medium.ttf
        weight: 500
      - asset: assets/fonts/qatar/Qatar2022Arabic-Bold.ttf
        weight: 700
      - asset: assets/fonts/qatar/Qatar2022Arabic-Heavy.ttf
        weight: 800
    
flutter_intl:
  enabled: true
