name: widam
description: Browse our products with ease and choose your favorite meat cut and complete your order by choosing your preferred payment method.

publish_to: 'none'

version: 20.0.5+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^7.9.2
  intl: ^0.19.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  flutter_native_splash: ^2.3.10
  flutter_svg: ^2.0.15
  google_maps_flutter: ^2.10.0
  modal_bottom_sheet: ^3.0.0
  geocoding: ^2.2.2
  uuid: ^4.5.1
  dio: ^5.7.0
  geolocator: ^13.0.2
  mockito: ^5.4.4
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  dots_indicator: ^3.0.0
  pull_to_refresh: ^2.0.0
  queen_validators: ^1.0.1  
  flutter_staggered_grid_view: ^0.7.0
  pinput: ^3.0.1
  timer_count_down: ^2.2.2
  easy_stepper: ^0.8.2
  flutter_keyboard_visibility: ^6.0.0
  dotted_border: ^2.1.0
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  url_launcher: ^6.2.4
  package_info_plus: ^8.1.1
  webview_flutter: ^4.4.4
  pay: ^1.1.2
  fcm_config: 
    path: local_packages/fcm_config
  store_redirect: ^2.0.3
  flutter_html: ^3.0.0-beta.2
  flutter_barcode_scanner:
    git:
      url: https://github.com/AmolGangadhare/flutter_barcode_scanner
      ref: 379ded73012f1221a372edba8867ac3341b27f9e
  firebase_crashlytics: ^4.1.5
  firebase_core: ^3.8.0
  onboarding_overlay: ^3.2.2
  flutter_rating_bar: ^4.0.1
  widget_to_marker: ^1.0.6
  flutter_polyline_points_plus: ^3.0.0
  step_progress_indicator: ^1.0.2
  synchronized: ^3.3.0
  flutter_vibrate: ^1.3.0
  flutter_cupertino_date_picker_fork: ^1.0.7
  firebase_database: ^11.1.6
  firebase_ui_database: ^1.5.0
  firebase_auth: ^5.3.3
  status_bar_control: ^3.2.1
  flutter_chat_bubble: ^2.0.2
  firebase_analytics: ^11.3.5
  map_launcher: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.13
  riverpod_generator: ^2.3.9
  flutter_gen_runner: ^5.8.0
  riverpod_lint: ^2.3.7
  custom_lint: ^0.5.11
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/app_icon/app_icon.png"
  remove_alpha_ios: true

flutter_gen:
  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/splash/logo.png
    - assets/splash/splash.gif

  fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        weight: 400
      - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        weight: 700
      - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
        weight: 800
  - family: Qatar
    fonts:
      - asset: assets/fonts/qatar/Qatar2022Arabic-Thin.ttf
        weight: 100
      - asset: assets/fonts/qatar/Qatar2022Arabic-Book.ttf
        weight: 400
      - asset: assets/fonts/qatar/Qatar2022Arabic-Medium.ttf
        weight: 500
      - asset: assets/fonts/qatar/Qatar2022Arabic-Bold.ttf
        weight: 700
      - asset: assets/fonts/qatar/Qatar2022Arabic-Heavy.ttf
        weight: 800
    
flutter_intl:
  enabled: true
